- name: urotaxi application
  hosts: all
  tasks: 
  - name: install jdk11
    apt: 
      name: openjdk-11-jdk
      state: present
      update_cashe: yes
    become: yes
    become_method: sudo
  - name: create directory middleware
    file: 
      path: /u01/middleware
      state: directory
      owner: ubuntu
      group: ubuntu
    become: yes
    become_method: sudo  