- name: urotaxi application
  hosts: all
  vars: 
    TOMCAT_DOWNLOAD_URL: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.82/bin/apache-tomcat-9.0.82.tar.gz"
    TOMCAT_HOME_DIR: "/u01/middleware/apache-tomcat-9.0.82"
  tasks: 
    - name: install jdk11
      apt: 
        name: openjdk-11-jdk
        state: present
        update_cache: yes
      become: yes
      become_method: sudo
    - name: create directory middleware
      file: 
        path: /u01/middleware
        state: directory
        owner: ubuntu
        group: ubuntu
      become: yes
      become_method: sudo  
    - name: download tomcat
      get_url:
        url: "{{TOMCAT_DOWNLOAD_URL}}"
        dest: /u01/middleware
    - name: unarchive tomcat
      unarchive: 
        src: /u01/middleware/apache-tomcat-9.0.82.tar.gz
        dest: /u01/middleware/
        remote_src: true
    - name: find jdk
      shell: readlink -f $(which java) | sed 's/bin.*//g'
      register: JAVA_HOME
    - name: Install PyMySQL
      package:
        name: python3-pymysql
        state: present
        update_cache: yes
      become: yes
      become_method: sudo
    - name: install mysql client
      apt:
        name: mysql-client-8.0
        state: present
        update_cache: yes
      become: yes
      become_method: sudo    
    - name: tomcat service
      template:
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      become: yes
      become_method: sudo
      notify:
        - tomcatreload
    - name: copy db schema
      copy:
        src: "{{ lookup('env','WORKSPACE') }}/src/main/db/urotaxidb.sql"
        dest: /tmp/

    - name: create schema
      community.mysql.mysql_db:
        name: all
        state: import
        target: /tmp/urotaxidb.sql
        login_host: "{{ lookup('env','DB_HOST') }}"
        login_user: "{{ lookup('env','UROTAXI_DB_USR') }}"
        login_password: "{{ lookup('env','UROTAXI_DB_PSW') }}"
        #config_file: no 
    - name: Deploy        
      copy: 
        src: "{{ lookup('env','WORKSPACE') }}/target/urotaxi.war"
        dest: /u01/middleware/apache-tomcat-9.0.82/webapps/  
      notify: 
        - tomcatrestart    
  handlers:
    - name: tomcatreload
      service:
        name: tomcat
        state: reloaded
        enabled: yes
      become: yes
      become_method: sudo
    - name: tomcatrestart
      service:
        name: tomcat restart
        state: restarted
      become: yes
      become_method: sudo

















        

        

            